language: csharp

env:
  global:
    - secure: "nggoV4YviK2uPOvcCsAMwhyzGwPLmHboD28ToPwJWbSm3qjfFwcZ0xBzPwDXktlEPh53PJOM4J8vbIaFEjI0vS7H2fw95uhCtOMsSbnsAVUkw+RtxFZ5ZniWtTrZp31QXIoOSzsXh3DMv1MjMx83/OW9AjW9UauTuP1Q2o6W9LuxqScjMlOaCYEFFDIU/SJnEtCkIi+C9mNWn2jrVFpllehsOqVrxoqpGvQU8cv1X3D3bz5Prii2dmTXXOHfdhU8wgbklU/lZD9gOzA9asm9ypGxJ815Hdh1NjeWHcv39zq+bc3aOtgq3+iRy2dC9dQBOu5xLUnqNdxYNgtL/GyTGg1yiXC2Cw8nIjlyqsfqtBo5cBo5NuyVsJEEkZXgD9eRl8ACaMIjVkLiPydLeKNPZhPRRgji3vjvyxfSd0hdrongtZhxucpBLLFUd+1xBGSZ+42GLUfpXIObFXqLFeWQI5ZEyYdLlqCcQLo2cSGRmJsY41pTbfegStmchVgiHtr/qIePL1AJ4GG5GI1AdFU4I1qEeFj5gFKwhU28PDWVL7ZU75aH8TME6lcLRx5m05Z/SI7mmbMJAlP3Ejeo/i8J96Vmayk9gLymvtWVfmxgTA71iqmQuH9U1EeF3oWpleSaiS2okAPtLuB1tlGyTLrgRLx45STsycZKZa+/9JdbFF8="

script:
  - dotnet pack src/Tmds.DotnetOC --configuration Release --version-suffix "$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER" --output .

after_success:
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.DotnetOC/Tmds.DotnetOC.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
     fi'